compute_environment: LOCAL_MACHINE
debug: false

fsdp_config:
  fsdp_activation_checkpointing: false
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true

distributed_type: "FSDP" # DeepSpeed, FSDP
downcast_bf16: "no"
enable_cpu_affinity: false
machine_rank: 0
# main_process_ip: 127.0.0.1
# main_process_port: 23456
# main_training_function: main
mixed_precision: "no" # bf16, fp16
num_machines: 1
num_processes: 2
