compute_environment: LOCAL_MACHINE
debug: false
distributed_type: null # DeepSpeed, FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
# main_process_ip: 127.0.0.1
# main_process_port: 23456
# main_training_function: main
mixed_precision: "no" # bf16, fp16
num_machines: 1
num_processes: 1
